# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeHjnkcHNiLow1mLtSX0a6fx28-HfAq3

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

ans=s.split()
ans

"""*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("The diameter of {0} is {1} kilometers .".format (planet , diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

array=np.zeros(10)

array=np.ones(10)*5

"""## 5. Create an array of all the even integers from 20 to 35"""

array=np.arange(20,35,2)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b), axis=0)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data = [[1, 'Praabindh'], [2, 'Princy'], [3, 'Pranav']]
df = pd.DataFrame(data, columns=['SN', "Name"])
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import datetime

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df=pd.DataFrame(lists,columns=['SI','Tag','Number'])
print(df)